server:
  port: 8080

spring:
  application:
    name: takeout
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: root
  redis:
    host: 192.168.119.133
    port: 6379
    database: 0
    cache:
      redis:
        time-to-live: 3600000 #设置存活时间为一小时，如果不设置，则一直存活
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

takeout:
  path: D:\img\